# Jekyll configuration

title: Ty Darnell
description: |
  MS Biostatistics UNC May 2020
author:
  - name: Ty Darnell
    url: "tydarnell.github.io"
navbar:
  title: "Ty Darnell"
  left:
    - text: "Resume"
      href: https://tydarnell.github.io/TyDarnell-Resume.pdf
  right:
    - icon: fa-github fa-lg
      href: http://github.com/tydarnell
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/tydarnell

# Build Settings

theme: jekyll-theme-cayman
